### ISSUE TITLE
ubuntuに日本語が対応してない。

### ISSUE THREAD

**Issue by ghost** [Amano123/elasticsearch_ubuntu18.04#2]
ubuntuに日本語が対応しておらず、文字化けします。
そのせいでエラーになることはありませんが、プログラムの説明が全て読めない。。。

パッケージを入れようにもpassが、、、。

**Comment by Amano123** [comment]
ubuntuの中身の言語が英語の設定のままでした。
日本語に変更してあるので試してみてください。
また、passはubuntuのdockerfileを読むとわかると思います。

**Comment by ghost** [comment]
ありがとう
